export { HomeView } from "./home";
export { BasicsView } from "./basics";
export { RoadmapView } from "./roadmap";
export { TeamView } from "./team";
export { TechView } from "./tech";
export { TerminalView } from "./terminal";
export { LandingView } from "./landing";
export { StakingView } from "./staking";
export { ArtView } from "./art";
